language: go

go:
  - 1.4
  - 1.5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam0g-dev
  - go get github.com/msteinert/pam 

install:
  - go get -t -v ./...

script: go build -v -tags "pam"

